-- Simple Queries
SELECT count(*) FROM ICE_DB.PUBLIC.ICEBERG_TAXI_TRIP;


-- Medium Queries
SELECT AVG((TPEP_DROPOFF_DATETIME - TPEP_PICKUP_DATETIME) / 60) AS AVG_DURATION_MINUTES
FROM ICE_DB.PUBLIC.ICEBERG_TAXI_TRIP;


SELECT PULOCATIONID, AVG(FARE_AMOUNT) AS AVG_FARE
FROM ICE_DB.PUBLIC.ICEBERG_TAXI_TRIP
GROUP BY PULOCATIONID 
ORDER BY AVG_FARE DESC;


SELECT "puYear", "puMonth", "totalAmount"
FROM (
    SELECT "puYear", "puMonth", "totalAmount", ROW_NUMBER() OVER (partition by "puYear", "puMonth" order by "totalAmount") as rn
    FROM ICE_DB.PUBLIC.ICEBERG_TAXI_TRIP
) ranked
WHERE ranked.rn = 1;


-- Hard Queries
SELECT count(*)
FROM (
SELECT *
FROM ICEBERG_TAXI_TRIP
GROUP BY ALL
) a ;


SELECT COUNT(*)
FROM (
    SELECT DISTINCT * 
    FROM ICEBERG_TAXI_TRIP_ORDERED
) a;
